require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'

Rails:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%w': '[]'

Style/StringLiterals:
  Exclude:
    - 'config/**/*'

Style/Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'db/migrate/*'

RSpec/NestedGroups:
  Max: 5

Style/MixinUsage:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/views/**/*'
