language: ruby

dist: xenial

services:
  - postgresql

addons:
  postgresql: "10"

cache:
  bundler: true
  directories:
    - ~/.rvm
    - ~/.cache

rvm:
  - 2.6.5

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
  - psql -c 'create database travis_ci_test;' -U postgres

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
